runtime: python39

env_variables:
  # Insert an API key with access to the Cloud Scheduler API here
  API_KEY: ""

# Handlers define how to route static requests to your application.
handlers:
- url: /local_components/
  static_dir: local_components/

# Default Polymer Components
- url: /components/
  static_dir: components/

# Static files
- url: /static/
  static_dir: static/
